spring:
  profiles:
    active: @profileActive@
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=final_project_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
server:
  port: 80


---
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/user_service?currentSchema=final_project_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

