spring:
  profiles:
    active: @profileActive@
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/event_service?currentSchema=final_project
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
server:
  port: 82

users:
  service:
    url: http://localhost:80/users

classifier:
  service:
    url: http://localhost:81/classifier
---
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/event_service?currentSchema=final_project
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

users:
  service:
    url: http://user-service:80/users

classifier:
  service:
    url: http://classifier-service:81/classifier